cutadapt:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    --minimum-length 20

star:
  index: '/path/to/index'
  extra: ''
  threads: 8

sambamba_sort:
  extra: ''
  threads: 8

picard_merge_bam:
  extra: ''

sambamba_index:

feature_counts:
  annotation: '/path/to/gtf'
  extra: ''
  threads: 5

fastqc:
  extra: ''
