################################################################################
# Pipeline options                                                             #
################################################################################

options:
  pdx: False


################################################################################
# Input configuration                                                          #
################################################################################

input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: 'input'

  # Optional: configuration to use for remote (FTP) input files.
  # ftp:
  #   username: 'user'
  #   password: 'pass'


################################################################################
# Rule configuration                                                           #
################################################################################

#### General/shared rules ####

# Single-end config for cutadapt.
cutadapt_se:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    --minimum-length 20

# Paired-end config for cutadapt.
cutadapt_pe:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    -q 20
    --minimum-length 20

star:
  index: '/path/to/index'
  # Host genome index, only required for PDX processing.
  # index_host: '/path/to/host_index'
  readgroup: >-
    ID:{sample}.{lane} SM:{sample} LB:{sample}
    PU:{sample}.{lane} PL:ILLUMINA CN:CENTRE
  extra: ""
  threads: 10

sambamba_sort:
  extra: ''
  threads: 10

samtools_merge:
  extra: ''
  threads: 10

feature_counts:
  annotation: '/path/to/gtf'
  extra: ''
  threads: 5

multiqc:
  extra: ''

fastqc:
  extra: ''

#### PDX-specific rules ####

disambiguate:
  extra: ''
