
cutadapt:
  options:
    '-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC --minimum-length 20'

star:
  index: '/path/to/index'
  extra: ''
  threads: 8

sambamba_sort:
  params: ''
  threads: 8

sambamba_index:

feature_counts:
  annotation: '/path/to/gtf'
  extra: ''
