input:
  dir: 'input'
  # ftp:
  #   username: 'user'
  #   password: 'pass'

paired: True

# Single-end config for cutadapt.
cutadapt:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    --minimum-length 20

# Paired-end config for cutadapt.
# cutadapt:
#   extra: >-
#     -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
#     -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
#     -q 20
#     --minimum-length 20

star:
  index: '/path/to/index'
  extra: ''
  threads: 10

sambamba_sort:
  extra: ''
  threads: 10

samtools_merge:
  extra: ''
  threads: 10

feature_counts:
  annotation: '/path/to/gtf'
  extra: ''
  threads: 5

multiqc:
  extra: ''

fastqc:
  extra: ''
